### PR TITLE
Update for Swift 2.0

### PR DESCRIPTION
**Pull request by TeunVR**
Small fixes to make it Swift 2.0 compatible

### CODE REVIEW

**Comment by dbettermann** [comment]
Thanks for the pull request.

I'm going to keep any Swift 2.0 changes out of the master branch until Xcode 7 comes out of beta. I will accept your Swift 2.0 specific changes on a swift-2.0 branch.

Are the `public` modifiers on the class something with Swift 2.0, or is that just something I missed? If the modifiers are not related to Swift 2.0 I would rather have them in a different commit.

Thanks again!

**Comment by TeunVR** [comment]
It might not entirely be related to swift-2.0, but the changes were necessary to use the cocoapods version in combination with the use_frameworks! setting in the Podfile.
Without specifying the public access modifier, the DBAlertController is not visible.

**Comment by dbettermann** [comment]
Makes sense.

Would you mind creating a separate pull request for the `public` modifiers? I can merge that one into master and then create a branch for the Swift 2.0 pull request.

Just want to keep the commits/branches accurate and make sure you get the credit.

**Comment by TeunVR** [comment]
Oh this change is so small, you can just change it in your code directly. I don't have time at the moment to split the commit. You can just close this pull request.

**Comment by dbettermann** [comment]
Ok. Thank you for the changes. I appreciate it.

**Pull request closed without merging**
